services:
  sdvn-klein:
    image: thanhlam00290/sdvn-klein:latest
    container_name: sdvn-klein

    gpus: all

    ports:
      - "8675:8675"

    environment:
      HF_TOKEN: "${HF_TOKEN}"

    volumes:
      - ./models:/data/models
      - ./datasets:/data/datasets
      - ./outputs:/data/outputs
      - ./logs:/data/logs
      - ./hf-cache:/data/hf-cache
      - ./aitk_db.db:/app/SDVN-training-colab-flux/aitk_db.db

    shm_size: "16g"

    networks:
      - sdvn-net

    restart: unless-stopped

  cloudflared-sdvn:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-sdvn

    depends_on:
      - sdvn-klein

    command:
      - tunnel
      - --no-autoupdate
      - --url
      - http://sdvn-klein:8675

    networks:
      - sdvn-net

    restart: unless-stopped
  
  # Cloudflare Tunnel riêng cho Filebrowser
  cloudflared-filebrowser:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-filebrowser
    command: tunnel --no-autoupdate --url http://filebrowser:80
    restart: unless-stopped
    depends_on:
      - filebrowser
  
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    ports:
      - "8080:80"
    volumes:
      - ./:/srv
    restart: unless-stopped


networks:
  sdvn-net:
    name: sdvn-net
    driver: bridge